# Generated by Django 3.1.4 on 2020-12-17 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(help_text='Longin...', max_length=100)),
                ('password', models.CharField(help_text='Mot de passe...', max_length=100)),
                ('role', models.CharField(blank=True, choices=[('e', 'Enseignant'), ('a', 'Apprenant')], default='a', max_length=1)),
            ],
        ),
    ]
